Repository wanted-team2/2week_RequestAQuoteDashboard, pull requests merged in 2022-02, with the labels that each got.

#7 ✨ Feat: 해더 구현
  src/App.tsx
  src/assets/company.png
  src/assets/company.svg
  src/assets/hamburger.svg
  src/assets/logo.svg
  src/components/base/Button/Button.tsx
  src/components/base/Button/Style.ts
  src/components/base/Buttons/Buttons.tsx
  src/components/base/Header/Header.tsx
  src/components/base/Header/Style.ts
  src/components/base/index.ts
  src/styles/commonStyles.ts
  src/styles/fonts.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: Feat

#8 Feat: Card 구현
  src/App.tsx
  src/components/base/Card/Card.tsx
  src/components/base/Card/Style.ts
  src/components/base/index.ts
  src/styles/theme.ts
Labels: UI, Feat

#10 :sparkles: Feat: 토글버튼 구현
  src/components/base/Toggle/Style.ts
  src/components/base/Toggle/Toggle.tsx
  src/components/base/index.ts
  src/hooks/useToggle.ts
Labels: Feat

#13 :sparkles: Feat: EmptyBox 컴포넌트 구현
  src/components/base/EmptyBox/EmptyBox.tsx
  src/components/base/EmptyBox/Style.ts
  src/components/base/index.ts
Labels: UI, Feat

#11 Feat: Dropdown, Dropdowns 컴포넌트 구현
  src/App.tsx
  src/assets/arrowDropDown.png
  src/assets/arrowDropDown.svg
  src/assets/index.ts
  src/components/base/Dropbox/Dropbox.tsx
  src/components/base/Dropbox/Style.ts
  src/components/base/Dropdown/Dropdown.tsx
  src/components/base/Dropdown/Style.ts
  src/components/base/index.ts
  src/components/domain/Dropdowns/Dropdowns.tsx
  src/components/domain/Dropdowns/Style.ts
  src/components/domain/index.ts
  src/hooks/index.ts
  src/hooks/useClickAway.ts
  src/hooks/useToggle.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
  src/utils/functions/index.ts
  tsconfig.paths.json
Labels: Feat, Refactor

#16 :recycle: (Refactoring: CardProps Partial 타입으로 수정/ join 함…
  src/components/base/Card/Card.tsx
Labels: Refactor

#18 :recycle: Refactor: methodList, materialList 상위로 분리
  src/components/base/Dropdown/Dropdown.tsx
  src/components/domain/Dropdowns/Dropdowns.tsx
  src/pages/Home/Home.tsx
  src/utils/functions/index.ts
Labels: Refactor

#25 :lipstick: Ui: Mobile ui 적용
  src/assets/hamburger.svg
  src/components/base/Dropdown/Style.ts
  src/components/base/Header/Header.tsx
  src/components/base/Header/Style.ts
  src/components/domain/Dropdowns/Style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/Style.ts
Labels: UI
